# Generated by Django 6.0.4 on 2026-04-18 10:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('restaurant_name', models.CharField(max_length=120)),
                ('external_platform', models.CharField(blank=True, max_length=50)),
                ('external_reference', models.CharField(blank=True, max_length=100)),
                ('meeting_point', models.CharField(max_length=120)),
                ('meeting_notes', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked'), ('IN_PROGRESS', 'In Progress'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('max_participants', models.PositiveSmallIntegerField(default=6)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('other_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_settled', models.BooleanField(default=False)),
                ('cutoff_at', models.DateTimeField()),
                ('expected_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_instructions', models.CharField(blank=True, max_length=255)),
                ('external_item_reference', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_order_items', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CREATOR', 'Creator'), ('JOINER', 'Joiner')], default='JOINER', max_length=10)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('JOINED', 'Joined'), ('PAID', 'Paid'), ('LEFT', 'Left'), ('REFUNDED', 'Refunded'), ('HANDED_OVER', 'Handed Over')], default='JOINED', max_length=20)),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoverOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_hash', models.CharField(max_length=128)),
                ('code_last4', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('VERIFIED', 'Verified'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_handover_otps', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_otps', to='orders.order')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover_otp', to='orders.orderparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked'), ('IN_PROGRESS', 'In Progress'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('to_status', models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked'), ('IN_PROGRESS', 'In Progress'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_state_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['meeting_point'], name='orders_orde_meeting_e476e4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['cutoff_at'], name='orders_orde_cutoff__42755e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('max_participants__gt', 0)), name='orders_order_max_participants_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_amount__gte', 0)), name='orders_order_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('platform_fee__gte', 0)), name='orders_order_platform_fee_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_fee__gte', 0)), name='orders_order_delivery_fee_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('other_fee__gte', 0)), name='orders_order_other_fee_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='orders_order_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='orders_item_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='orders_item_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='orders_item_line_total_non_negative'),
        ),
        migrations.AddIndex(
            model_name='orderparticipant',
            index=models.Index(fields=['status'], name='orders_orde_status_d8e757_idx'),
        ),
        migrations.AddIndex(
            model_name='orderparticipant',
            index=models.Index(fields=['role'], name='orders_orde_role_6dfe7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderparticipant',
            constraint=models.UniqueConstraint(fields=('order', 'user'), name='orders_orderparticipant_unique_member'),
        ),
        migrations.AddConstraint(
            model_name='orderparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('amount_due__gte', 0)), name='orders_participant_due_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='orders_participant_paid_non_negative'),
        ),
        migrations.AddIndex(
            model_name='handoverotp',
            index=models.Index(fields=['status'], name='orders_hand_status_55757b_idx'),
        ),
        migrations.AddIndex(
            model_name='handoverotp',
            index=models.Index(fields=['expires_at'], name='orders_hand_expires_657fde_idx'),
        ),
        migrations.AddConstraint(
            model_name='handoverotp',
            constraint=models.CheckConstraint(condition=models.Q(('failed_attempts__gte', 0)), name='orders_handoverotp_failed_attempts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='handoverotp',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gt', 0)), name='orders_handoverotp_max_attempts_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_1de1d7_idx'),
        ),
    ]
