# Generated by Django 6.0.4 on 2026-04-18 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='organisations.campus'),
        ),
        migrations.AddField(
            model_name='order',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='organisations.organisation'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organisation', 'campus'], name='orders_orde_organis_ab8a8a_idx'),
        ),
    ]
