# Generated by Django 6.0.4 on 2026-04-19 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("organisations", "0002_pickuppoint"),
		("orders", "0002_order_campus_order_organisation_and_more"),
	]

	operations = [
		migrations.AddField(
			model_name="order",
			name="pickup_point",
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.PROTECT,
				related_name="orders",
				to="organisations.pickuppoint",
			),
		),
	]
