# Generated by Django 6.0.4 on 2026-04-19 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_participant_for_items(apps, schema_editor):
	OrderItem = apps.get_model("orders", "OrderItem")
	OrderParticipant = apps.get_model("orders", "OrderParticipant")

	for item in OrderItem.objects.all().iterator():
		participant = OrderParticipant.objects.filter(
			order_id=item.order_id,
			user_id=item.added_by_id,
		).first()
		if participant is None:
			participant = OrderParticipant.objects.filter(
				order_id=item.order_id,
				role="CREATOR",
			).first()
		if participant:
			item.participant_id = participant.id
			item.save(update_fields=["participant"])


class Migration(migrations.Migration):

	dependencies = [
		("orders", "0003_order_pickup_point"),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.AddField(
			model_name="orderitem",
			name="participant",
			field=models.ForeignKey(
				null=True,
				on_delete=django.db.models.deletion.CASCADE,
				related_name="items",
				to="orders.orderparticipant",
			),
		),
		migrations.AddField(
			model_name="orderitem",
			name="review_reason",
			field=models.CharField(blank=True, max_length=255),
		),
		migrations.AddField(
			model_name="orderitem",
			name="reviewed_at",
			field=models.DateTimeField(blank=True, null=True),
		),
		migrations.AddField(
			model_name="orderitem",
			name="reviewed_by",
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.SET_NULL,
				related_name="reviewed_order_items",
				to=settings.AUTH_USER_MODEL,
			),
		),
		migrations.AddField(
			model_name="orderitem",
			name="status",
			field=models.CharField(
				choices=[
					("DRAFT", "Draft"),
					("SUBMITTED", "Submitted"),
					("APPROVED", "Approved"),
					("REJECTED", "Rejected"),
				],
				default="DRAFT",
				max_length=20,
			),
		),
		migrations.RunPython(create_participant_for_items, migrations.RunPython.noop),
		migrations.AlterField(
			model_name="orderitem",
			name="participant",
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name="items",
				to="orders.orderparticipant",
			),
		),
		migrations.AddIndex(
			model_name="orderitem",
			index=models.Index(fields=["order", "status"], name="orders_item_order_i_65d952_idx"),
		),
		migrations.AddIndex(
			model_name="orderitem",
			index=models.Index(fields=["participant", "status"], name="orders_item_partic_094728_idx"),
		),
	]
