# Generated by Django 6.0.4 on 2026-04-18 22:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_orderitem_workflow_fields"),
        (
            "organisations",
            "0003_rename_organisatio_organis_f4f46f_idx_organisatio_organis_7e6e99_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="orderitem",
            new_name="orders_orde_order_i_3360fc_idx",
            old_name="orders_item_order_i_65d952_idx",
        ),
        migrations.RenameIndex(
            model_name="orderitem",
            new_name="orders_orde_partici_d6c89c_idx",
            old_name="orders_item_partic_094728_idx",
        ),
        migrations.AddField(
            model_name="order",
            name="base_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="min_threshold_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="max_participants",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_threshold_amount__gte", 0)),
                name="orders_order_min_threshold_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_amount__gte", 0)),
                name="orders_order_base_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("review_reason__isnull", False),
                    ("review_reason", ""),
                    _connector="OR",
                ),
                name="orders_item_review_reason_valid",
            ),
        ),
    ]
