# Generated by Django 6.0.4 on 2026-04-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0005_rename_orders_item_order_i_65d952_idx_orders_orde_order_i_3360fc_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("LOCKED", "Locked"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DELIVERED", "Delivered"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("WITHDRAWN", "Withdrawn"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("LOCKED", "Locked"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DELIVERED", "Delivered"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("WITHDRAWN", "Withdrawn"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("LOCKED", "Locked"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DELIVERED", "Delivered"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("WITHDRAWN", "Withdrawn"),
                ],
                max_length=20,
            ),
        ),
    ]
