# Generated by Django 6.0.4 on 2026-04-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_order_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("LOCKED", "Locked"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DELIVERED", "Delivered"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("PLACED", "Placed"),
                    ("ARRIVED", "Arrived"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("LOCKED", "Locked"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DELIVERED", "Delivered"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("PLACED", "Placed"),
                    ("ARRIVED", "Arrived"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("LOCKED", "Locked"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DELIVERED", "Delivered"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("PLACED", "Placed"),
                    ("ARRIVED", "Arrived"),
                ],
                max_length=20,
            ),
        ),
    ]
