# Generated by Django 6.0.4 on 2026-04-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
