# Generated by Django 6.0.4 on 2026-04-18 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_campus_order_organisation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('category', models.CharField(choices=[('PAYMENT_ISSUE', 'Payment Issue'), ('ITEM_MISMATCH', 'Item Mismatch'), ('CANCELLATION', 'Cancellation Dispute'), ('DELIVERY', 'Delivery Issue'), ('QUALITY', 'Quality Complaint'), ('OTHER', 'Other')], max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In Review'), ('UNDER_NEGOTIATION', 'Under Negotiation'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='OPEN', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='URLs or file references for evidence')),
                ('amount_claimed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('resolution_type', models.CharField(blank=True, choices=[('AUTO_REFUND', 'Auto Refund'), ('PARTIAL_REFUND', 'Partial Refund'), ('FULL_REFUND', 'Full Refund'), ('REPLACEMENT', 'Replacement Order'), ('NO_ACTION', 'No Action Needed')], max_length=50, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text="Admin's decision and explanation")),
                ('is_escalated', models.BooleanField(default=False)),
                ('escalation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='orders.order')),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In Review'), ('UNDER_NEGOTIATION', 'Under Negotiation'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], max_length=30)),
                ('new_status', models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In Review'), ('UNDER_NEGOTIATION', 'Under Negotiation'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], max_length=30)),
                ('change_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_changes', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='disputes.dispute')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('USER', 'User Message'), ('ADMIN', 'Admin Response'), ('SYSTEM', 'System Notification')], default='USER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='disputes.dispute')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Executed')], default='PENDING', max_length=20)),
                ('refund_transaction_id', models.CharField(blank=True, help_text='Razorpay refund ID', max_length=100)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='disputes.dispute')),
                ('replacement_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_replacements', to='orders.order')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-resolved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['ticket_id'], name='disputes_di_ticket__12402c_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['order', 'status'], name='disputes_di_order_i_7f3b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['raised_by', 'status'], name='disputes_di_raised__1384e4_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['assigned_to', 'status'], name='disputes_di_assigne_eb5d18_idx'),
        ),
        migrations.AddIndex(
            model_name='disputehistory',
            index=models.Index(fields=['dispute', 'created_at'], name='disputes_di_dispute_76ae66_idx'),
        ),
        migrations.AddIndex(
            model_name='disputemessage',
            index=models.Index(fields=['dispute', 'created_at'], name='disputes_di_dispute_933084_idx'),
        ),
    ]
