# Generated by Django 6.0.4 on 2026-04-19 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disputes", "0001_initial"),
        ("orders", "0008_alter_order_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispute",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disputes",
                to="orders.order",
            ),
        ),
    ]
