# Generated by Django 6.0.4 on 2026-04-19 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("organisations", "0001_initial"),
	]

	operations = [
		migrations.CreateModel(
			name="PickupPoint",
			fields=[
				("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
				("name", models.CharField(max_length=120)),
				("slug", models.SlugField(blank=True, max_length=140)),
				("description", models.CharField(blank=True, max_length=255)),
				("is_active", models.BooleanField(default=True)),
				("sort_order", models.PositiveSmallIntegerField(default=0)),
				("metadata", models.JSONField(blank=True, default=dict)),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
				(
					"campus",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.CASCADE,
						related_name="pickup_points",
						to="organisations.campus",
					),
				),
				(
					"organisation",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="pickup_points",
						to="organisations.organisation",
					),
				),
			],
			options={
				"ordering": ["sort_order", "name"],
			},
		),
		migrations.AddConstraint(
			model_name="pickuppoint",
			constraint=models.UniqueConstraint(
				fields=("organisation", "slug"),
				name="organisations_pickuppoint_unique_org_slug",
			),
		),
		migrations.AddIndex(
			model_name="pickuppoint",
			index=models.Index(fields=["organisation", "is_active"], name="organisatio_organis_f4f46f_idx"),
		),
		migrations.AddIndex(
			model_name="pickuppoint",
			index=models.Index(fields=["campus", "is_active"], name="organisatio_campus__676c68_idx"),
		),
	]
