# Generated by Django 6.0.4 on 2026-04-18 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0002_pickuppoint"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pickuppoint",
            new_name="organisatio_organis_7e6e99_idx",
            old_name="organisatio_organis_f4f46f_idx",
        ),
        migrations.RenameIndex(
            model_name="pickuppoint",
            new_name="organisatio_campus__f0d771_idx",
            old_name="organisatio_campus__676c68_idx",
        ),
    ]
