# Generated by Django 6.0.4 on 2026-04-19 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("orders", "0004_orderitem_workflow_fields"),
		("payments", "0001_initial"),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name="PaymentRefund",
			fields=[
				("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
				("status", models.CharField(choices=[("CREATED", "Created"), ("PROCESSED", "Processed"), ("FAILED", "Failed")], default="CREATED", max_length=20)),
				("amount", models.DecimalField(decimal_places=2, max_digits=10)),
				("currency", models.CharField(default="INR", max_length=3)),
				("reason", models.CharField(blank=True, max_length=255)),
				("provider_refund_id", models.CharField(blank=True, max_length=100, null=True, unique=True)),
				("failed_reason", models.CharField(blank=True, max_length=255)),
				("gateway_payload", models.JSONField(blank=True, default=dict)),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
				("order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payment_refunds", to="orders.order")),
				("participant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payment_refunds", to="orders.orderparticipant")),
				("payment_transaction", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="refunds", to="payments.paymenttransaction")),
				("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payment_refunds", to=settings.AUTH_USER_MODEL)),
			],
			options={
				"ordering": ["-created_at"],
			},
		),
		migrations.AddIndex(
			model_name="paymentrefund",
			index=models.Index(fields=["order", "created_at"], name="payments_pa_order_i_d95f39_idx"),
		),
		migrations.AddIndex(
			model_name="paymentrefund",
			index=models.Index(fields=["participant", "status"], name="payments_pa_partici_a2c519_idx"),
		),
		migrations.AddIndex(
			model_name="paymentrefund",
			index=models.Index(fields=["status"], name="payments_pa_status_881d78_idx"),
		),
		migrations.AddConstraint(
			model_name="paymentrefund",
			constraint=models.CheckConstraint(condition=models.Q(amount__gt=0), name="payments_refund_amount_gt_zero"),
		),
	]
