# Generated by Django 6.0.4 on 2026-04-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
