# Generated by Django 6.0.4 on 2026-04-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hostel',
        ),
    ]
