# Generated by Django 6.0.4 on 2026-04-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_organisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="ifsc_code",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
