# Generated by Django 6.0.4 on 2026-04-19 17:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_google_id_alter_user_gender_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_penalty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
